### ISSUE TITLE
Friends list hiding some friends due to a very long status

### ISSUE THREAD

**Issue by RichardLaan** [KillYoy/DiscordNight#25] opened 2021-07-19 18:36 UTC
I am running discord at 840 pixels wide. I have a friend who always has a super long status, and it interacts with the theme's attempts to add multiple columns in such a way that it hides the other column. Note that only 4 friends are in the image, but discord says that there are 8 online.
![Bugged](https://user-images.githubusercontent.com/85661330/126209482-da160568-0bec-414c-9406-aeb9ebc78e8f.png)

This is the same friends list but at 1680 pixels wide. It isn't bugged but that one status is making one column much larger than the other ones, but is not hiding any friends.
![Fullscreen](https://user-images.githubusercontent.com/85661330/126209804-08770291-7425-4db3-a5b4-75cdcb09512b.png)

**Comment by KillYoy** [comment] 2021-07-19 19:02
I am not able to replicate this issue, make sure you disable all other themes that could be conflicting. I see that you have the RadialStatus theme enabled for example.

**Comment by KillYoy** [comment] 2021-07-20 22:33
This issue was indeed caused by the way RadialStatus is displaying its statuses. So I am closing this issue as it's not my themes fault for this conflict.

**Closed by KillYoy** 2021-07-20 22:33 UTC
